### ISSUE TITLE
Use without WiFi access?

### ISSUE THREAD

**Issue by GSVNoFixedabode** [Resinchem/standalone-led-controller#1]
Can this be used without having to connect to local WiFi? So flash the firmware, connect to the AP & configure PIR & LEDs but leave wifi blank?  Every time I try this it seems to wait for wifi config/connection and doesn't proceed further. Thanks

**Comment by Resinchem** [comment]
Unfortunately... no.  Not as it is currently written and developed.  The AP process does not have the capabilities to generate the web settings page, accept all the options and values and then write that to flash.  The AP process is basically just the process to get the device onto wifi.  And you are correct that the process will simply wait for a valid wifi connection before it proceeds.

It might be possible to rewrite the code, hardcode all your options into the code (e.g. number of LEDs, brightness, effect, number of PIRs, etc.) and avoid the use of wifi in that manner, but that is something you'd have to try on your own by forking or cloning this code and modifying accordingly.  As mentioned in the documentation, wifi is a requirement for this particular project.  Sorry... my current other projects and responsibilities simply won't allow me to develop a version that doesn't require wifi.
